import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

export class BatchOrderItemDto {
  @ApiProperty({ description: 'User defined information. Must be prefixed with t- and no longer than 28 bytes without t- prefix' })
  text: string;

  @ApiProperty({ description: 'Currency pair' })
  currency_pair: string;

  @ApiPropertyOptional({ description: 'Order Type', enum: ['limit', 'market'], default: 'limit' })
  type?: string;

  @ApiPropertyOptional({ description: 'Account type: spot - spot account, margin - leveraged account, unified - unified account', enum: ['spot', 'margin', 'unified'], default: 'spot' })
  account?: string;

  @ApiProperty({ description: 'Buy or sell order', enum: ['buy', 'sell'] })
  side: string;

  @ApiProperty({ description: 'Trading quantity' })
  amount: string;

  @ApiPropertyOptional({ description: 'Trading price, required when type=limit' })
  price?: string;

  @ApiPropertyOptional({ description: 'Time in force', enum: ['gtc', 'ioc', 'poc', 'fok'], default: 'gtc' })
  time_in_force?: string;

  @ApiPropertyOptional({ description: 'Amount to display for the iceberg order. Null or 0 for normal orders' })
  iceberg?: string;

  @ApiPropertyOptional({ description: 'Used in margin or cross margin trading to allow automatic loan of insufficient amount if balance is not enough' })
  auto_borrow?: boolean;

  @ApiPropertyOptional({ description: 'Enable or disable automatic repayment for automatic borrow loan generated by cross margin order. Default is disabled' })
  auto_repay?: boolean;

  @ApiPropertyOptional({ description: 'Self-Trading Prevention Action', enum: ['cn', 'co', 'cb', '-'], default: 'cn' })
  stp_act?: string;

  @ApiPropertyOptional({ description: 'Processing Mode: ACK | RESULT | FULL', enum: ['ACK', 'RESULT', 'FULL'], default: 'FULL' })
  action_mode?: string;
}
